#!/bin/bash

if ! hash pandoc 2> /dev/null; then
    echo "Pandoc does not appear to be installed"
    exit 1
fi

NEWFILENAME=`echo -n "$1" | sed -e 's/.md$/.html/'`
CSSFILE=`mktemp`
CSSINCLUDE="$CSSFILE"
ISCYGWIN=1

cat > "$CSSFILE" << 'CSSEOF'
<style type="text/css">
body {
    margin: 20px 60px;
    font-family: sans-serif;
}

blockquote {
    border-left: #004499 solid 6px;
    padding-left: 0.5em;
    margin-left: 2em;
}

h1, h2, h3, h4, h5, h6, h7 {
    color: #004499;
}

li {
    padding: 0.15em 0;
}

a {
    color: #004499;
}

div#TOC {
    border: #004499 dotted 2px;
    width: auto;
    margin: 10px;
    display: table;
    padding: 10px 30px 10px 10px;
    background-color: #eef8ff;
}
</style>
CSSEOF

if [[ $(uname -s) == CYGWIN* ]]; then
    CSSINCLUDE=`cygpath -w "$CSSFILE"`
    ISCYGWIN=0
fi

pandoc "$1" --standalone \
    --include-in-header="$CSSINCLUDE" --toc \
    --highlight-style pygments \
    --output="$NEWFILENAME"

PANDOCSUCCESS=$?

rm $CSSFILE

if [ $PANDOCSUCCESS ]; then
    if [ $ISCYGWIN ]; then
        cygstart "$NEWFILENAME"
    elif [[ $(hash xdg-open 2> /dev/null) && -z $DISPLAY ]]; then
        xdg-open "$NEWFILENAME"
    fi
fi

